"""
SRA 2026: Session 5 - Superior Grain Elevator Simulation
--------------------------------------------------------

WARNING:
This code is a SCAFFOLD, not a complete solution. It provides the basic
structural logic (entities, resources, generators) to get you started.
Real-world modeling often requires handling complexities not shown here,
such as shift changes, balking, or complex priority rules.

YOUR TASK:
1. Replace the placeholder values in the CONFIGURATION section.
2. Insert the correct Probability Distributions for arrivals and service
   times based on your analysis from Session 4.
3. Complete the logic to calculate financial costs.

GENERATED by GEMINI without access to the case or the data file.
"""

import simpy
import random
import numpy as np

# --- CONFIGURATION (STUDENT TO UPDATE) ---
# How many unloading bays does the elevator have?
NUM_BAYS = 1

# Cost per hour that a truck waits (Demurrage Cost)
HOURLY_WAIT_COST = 0.0  # TODO: Update from case data

# Simulation duration (e.g., minutes in a day or season)
SIM_TIME = 480

# --- DATA COLLECTION ---
wait_times = []

def truck_generator(env, elevator_resources):
    """Generates trucks arriving at the elevator."""
    i = 0
    while True:
        # STUDENT TODO: Replace the static value below with the distribution
        # you identified in Session 4 (e.g., random.expovariate, random.uniform).
        interarrival_time = 10
        yield env.timeout(interarrival_time)

        i += 1
        env.process(truck_process(env, f'Truck {i}', elevator_resources))

def truck_process(env, name, elevator_resources):
    """The lifecycle of a single truck: Arrive -> Wait -> Unload -> Depart."""
    arrival_time = env.now

    # Request a spot at the unloading bay
    with elevator_resources.request() as request:
        yield request

        # We have seized the bay. Calculate how long we waited.
        service_start_time = env.now
        wait = service_start_time - arrival_time
        wait_times.append(wait)

        # STUDENT TODO: Insert the Unloading Service Time distribution here.
        # Is it constant? Normal? Uniform?
        unload_time = 15  # Placeholder
        yield env.timeout(unload_time)

# --- MAIN EXECUTION ---
print("Starting Superior Grain Simulation...")
env = simpy.Environment()

# Create the elevator resource (The Server)
elevator = simpy.Resource(env, capacity=NUM_BAYS)

# Start the generator
env.process(truck_generator(env, elevator))

# Run the simulation
env.run(until=SIM_TIME)

# --- ANALYSIS ---
if wait_times:
    avg_wait = np.mean(wait_times)
    # STUDENT TODO: Ensure this cost calculation matches the case specifics
    total_cost = sum(wait_times) * (HOURLY_WAIT_COST / 60)  # Assuming minutes
else:
    avg_wait = 0
    total_cost = 0

print("Simulation Complete.")
print(f"Average Wait Time: {avg_wait:.2f} mins")
print(f"Total Season Demurrage Cost: ${total_cost:,.2f}")
