"""
SRA 2026: Session 6 - Mobile Blood Donor Clinic Simulation
----------------------------------------------------------

WARNING:
This code is a SCAFFOLD. It outlines the donor flow through the four stations.
Your goal is to parameterize it correctly and then modify the resource
structure to test "Pooled" vs. "Dedicated" staffing models.

GENERATED by GEMINI without access to the case or the data file.
"""

import simpy
import random

# --- CONFIGURATION (STUDENT TO UPDATE) ---
# Resource Capacities (How many staff/beds at each station?)
NUM_REGISTRATION = 1
NUM_NURSES_HISTORY = 1
NUM_DONOR_BEDS = 1
NUM_VOLUNTEERS = 1

# Process Times (Minutes) - Replace with Case Data
MEAN_REG_TIME = 5.0
MEAN_HISTORY_TIME = 10.0
MEAN_BLEED_TIME = 15.0
MEAN_REFRESH_TIME = 10.0

def donor_journey(env, name, clinic):
    """
    The journey of a donor through the mobile clinic stations.
    Flow: Registration -> History -> Donation -> Refreshment
    """
    arrival_time = env.now

    # --- STATION 1: REGISTRATION ---
    with clinic['registration'].request() as request:
        yield request
        # STUDENT TODO: Determine correct distribution for registration
        yield env.timeout(random.expovariate(1.0 / MEAN_REG_TIME))

    # --- STATION 2: HEALTH HISTORY ---
    # STUDENT TODO: In the "Pooled" scenario, you may need to change which
    # resource is requested here.
    with clinic['history_nurses'].request() as request:
        yield request
        yield env.timeout(random.expovariate(1.0 / MEAN_HISTORY_TIME))

    # --- STATION 3: DONOR ROOM (THE BLEED) ---
    with clinic['beds'].request() as request:
        yield request
        # STUDENT TODO: Is the bleed time random? Does it follow a Normal distribution?
        yield env.timeout(MEAN_BLEED_TIME)

    # --- STATION 4: REFRESHMENT ---
    with clinic['refreshment'].request() as request:
        yield request
        yield env.timeout(MEAN_REFRESH_TIME)

    total_time = env.now - arrival_time

def donor_generator(env, clinic):
    """Generates donors arriving at the clinic."""
    i = 0
    while True:
        # STUDENT TODO: Update arrival rate based on the case data
        yield env.timeout(random.expovariate(1.0 / 5.0))
        i += 1
        env.process(donor_journey(env, f'Donor {i}', clinic))

# --- MAIN EXECUTION ---
print("Starting Mobile Blood Donor Clinic Simulation...")
env = simpy.Environment()

# Dictionary to hold all our resources
clinic_resources = {
    'registration': simpy.Resource(env, capacity=NUM_REGISTRATION),
    'history_nurses': simpy.Resource(env, capacity=NUM_NURSES_HISTORY),
    'beds': simpy.Resource(env, capacity=NUM_DONOR_BEDS),
    'refreshment': simpy.Resource(env, capacity=NUM_VOLUNTEERS)
}

env.process(donor_generator(env, clinic_resources))
env.run(until=480)  # Run for an 8-hour shift

print("Simulation Complete. Check resource utilization and queue lengths.")
